#!/usr/bin/env python3
"""One-off bootstrap: derive tools/data-editor-dumps.json from the snapshot.

Recomputes, by exact byte comparison, which top-level DataEditorXML/*.txt dumps
are mechanically derivable from SC2GameDataComponents/, and writes the manifest
that tools/build-data-editor-dumps.py consumes.  Run once; the manifest is then
the committed specification.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "DataEditorXML"
SNAP = DATA / "SC2GameDataComponents"


def digest(blob: bytes) -> str:
    return hashlib.md5(blob).hexdigest()


def main() -> int:
    by_exact: dict[str, str] = {}
    by_stripped: dict[str, str] = {}
    for path in sorted(SNAP.rglob("*")):
        if not path.is_file():
            continue
        blob = path.read_bytes()
        rel = path.relative_to(SNAP).as_posix()
        by_exact.setdefault(digest(blob), rel)
        by_stripped.setdefault(digest(blob.rstrip(b"\n")), rel)

    dumps: dict[str, dict[str, str]] = {}
    manual: dict[str, str] = {}
    for path in sorted(DATA.glob("*.txt")):
        blob = path.read_bytes()
        if digest(blob) in by_exact:
            dumps[path.name] = {"source": by_exact[digest(blob)], "transform": "verbatim"}
        elif digest(blob) in by_stripped:
            dumps[path.name] = {
                "source": by_stripped[digest(blob)],
                "transform": "strip-trailing-newline",
            }
        else:
            manual[path.name] = "hand-maintained: no snapshot file matches this content"

    manifest = {
        "note": (
            "Derivation spec for DataEditorXML/*.txt. Generated by "
            "tools/_bootstrap-data-editor-dumps.py; regenerate the files with "
            "tools/build-data-editor-dumps.py --write."
        ),
        "snapshot_root": "DataEditorXML/SC2GameDataComponents",
        "dumps": dict(sorted(dumps.items())),
        "manual": dict(sorted(manual.items())),
    }
    target = ROOT / "tools" / "data-editor-dumps.json"
    target.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"derivable : {len(dumps)}")
    print(f"manual    : {len(manual)}  {sorted(manual)}")
    print(f"written   : {target.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
