#!/usr/bin/env python3
"""Pre-flight static validator for StarCraft II XML catalogs, UI layouts, and Galaxy scripts."""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

from sc2_paths import find_project_mods

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = REPO_ROOT / "tools" / "schemas" / "sc2-xsd"
CATALOG_XSD = SCHEMAS_DIR / "Catalog.xsd"
GAMEDATA_XSD = SCHEMAS_DIR / "GameData.xsd"
LAYOUT_XSD = SCHEMAS_DIR / "SC2Layout.xsd"

# Prohibited patterns in Galaxy scripts (SC2 custom script quirks)
# Note: +=, -=, *=, /=, %= ARE supported in Galaxy; only ++, -- and C-style for(;;) are not.
DISALLOWED_GALAXY_PATTERNS = [
    (re.compile(r"\bfor\s*\([^;]+;[^;]+;[^)]+\)"), "for (...) loop is unsupported in SC2 Custom Script; use while (...)"),
    (re.compile(r"\bbreak\s*;"), "break; is unsupported in SC2 Custom Script loops; use sentinel variables"),
    (re.compile(r"(?<![\w])\w+\s*(\+\+|\-\-)\s*[^;]*;"), "Post-increment/decrement (++, --) is unsupported in Galaxy Custom Script; use i += 1 or i -= 1"),
    (re.compile(r"[^\x00-\x7F]"), "Non-ASCII character detected in code (smart quotes, em-dashes, arrows, etc.)"),
]

GALAXY_PRIMITIVE_TYPES = {
    "int", "fixed", "bool", "string", "unit", "point", "region", "unitgroup",
    "playergroup", "trigger", "timer", "order", "wave", "doodad", "camerainfo",
    "sound", "text", "byte", "char", "color", "abilcmd", "actorscope", "actor",
    "revealer", "marker", "transmissionsource", "bank"
}


def find_local_mods(explicit: str | None = None) -> list[Path]:
    return find_project_mods(REPO_ROOT, explicit)


def find_script_blocks(mod_dirs: list[Path] | None = None) -> list[Path]:
    blocks: list[Path] = []
    selected_mods = mod_dirs if mod_dirs is not None else find_local_mods()
    # Mod-level custom script files (e.g. My_Main.galaxy included into compiled libs)
    for mod_dir in selected_mods:
        blocks.extend(mod_dir.glob("Base.SC2Data/*.galaxy"))
        scripts_dir = mod_dir / "Base.SC2Data" / "Scripts"
        if scripts_dir.is_dir():
            blocks.extend(scripts_dir.glob("*.galaxy"))
    # Workspace-root script block sources
    blocks.extend(REPO_ROOT.glob("*_ScriptBlock.galaxy"))
    if not blocks:
        blocks = list(REPO_ROOT.glob("*.galaxy"))
    # Skip compiled libraries (Lib*.galaxy and Lib*_h.galaxy) — generated by the Trigger Editor
    return sorted(
        {
            b.resolve()
            for b in blocks
            if b.is_file() and not b.stem.startswith("Lib")
        }
    )


def validate_xml_schemas(gamedata_dir: Path) -> tuple[list[str], str]:
    """Validate XML catalogs against XSD, failing closed if no backend exists."""
    issues: list[str] = []
    try:
        import lxml.etree as lxml_etree
    except ImportError:
        lxml_etree = None

    if not CATALOG_XSD.is_file():
        return [f"Required XSD schema not found: {CATALOG_XSD}"], "failed (schema missing)"

    if lxml_etree is not None:
        try:
            catalog_schema_doc = lxml_etree.parse(str(CATALOG_XSD))
            catalog_schema = lxml_etree.XMLSchema(catalog_schema_doc)
        except Exception as e:
            issues.append(f"Failed to compile Catalog.xsd schema: {e}")
            return issues, "failed compiling Catalog.xsd"

        gamedata_schema = None
        if GAMEDATA_XSD.is_file():
            try:
                gamedata_schema_doc = lxml_etree.parse(str(GAMEDATA_XSD))
                gamedata_schema = lxml_etree.XMLSchema(gamedata_schema_doc)
            except Exception as exc:
                issues.append(f"Failed to compile GameData.xsd schema: {exc}")
                return issues, "failed compiling GameData.xsd"

        checked_count = 0
        for xml_file in sorted(gamedata_dir.glob("*.xml")):
            try:
                doc = lxml_etree.parse(str(xml_file))
                root = doc.getroot()
                schema = gamedata_schema if root.tag == "Includes" and gamedata_schema is not None else catalog_schema
                if not schema.validate(doc):
                    for err in schema.error_log:
                        issues.append(
                            f"XSD Schema Error in {xml_file.name}:{err.line}: {err.message}"
                        )
                checked_count += 1
            except lxml_etree.XMLSyntaxError as e:
                issues.append(f"XML syntax error in {xml_file.name}: {e}")
        return issues, f"verified {checked_count} file(s) against XSD with lxml"

    xmllint = shutil.which("xmllint")
    if not xmllint:
        return (
            ["XSD validation unavailable: install lxml or provide xmllint on PATH."],
            "failed (no XSD backend)",
        )

    schema_groups: dict[Path, list[Path]] = {CATALOG_XSD: [], GAMEDATA_XSD: []}
    for xml_file in sorted(gamedata_dir.glob("*.xml")):
        try:
            root = ET.parse(xml_file).getroot()
        except ET.ParseError:
            # The ordinary XML parser reports this with a clearer message.
            continue
        schema_path = GAMEDATA_XSD if root.tag == "Includes" else CATALOG_XSD
        schema_groups[schema_path].append(xml_file)

    checked_count = 0
    for schema_path, xml_files in schema_groups.items():
        if not xml_files:
            continue
        result = subprocess.run(
            [
                xmllint,
                "--noout",
                "--schema",
                str(schema_path),
                *(str(xml_file) for xml_file in xml_files),
            ],
            capture_output=True,
            text=True,
        )
        checked_count += len(xml_files)
        if result.returncode != 0:
            detail = result.stderr.strip() or result.stdout.strip() or "validation failed"
            issues.append(f"XSD Schema Error ({schema_path.name}): {detail}")
    return issues, f"verified {checked_count} file(s) against XSD with xmllint"


def validate_catalog_root(root: ET.Element, file_name: str) -> list[str]:
    """Apply project XML rules to one already-parsed catalog tree."""
    issues: list[str] = []
    if root.tag == "Catalog" and not any(isinstance(child.tag, str) for child in root):
        issues.append(f"Comment-only catalog in {file_name}: at least one catalog entry is required.")

    for elem in root.iter():
        if elem.tag is ET.Comment:
            comment = elem.text or ""
            if any(ord(char) > 127 for char in comment):
                issues.append(f"Non-ASCII XML comment in {file_name}: {comment.strip()[:80]}")
            continue
        if not isinstance(elem.tag, str):
            continue

        if "AbilAutoCmd" in elem.tag:
            issues.append(
                f"Schema violation in {file_name}: '<{elem.tag}>' is invalid in SC2 XML schema."
            )

        if elem.tag == "CBehaviorBuff":
            for child in elem:
                if child.tag == "InitEffect" or child.attrib.get("id") == "InitEffect":
                    issues.append(
                        f"Schema violation in {file_name} (id='{elem.attrib.get('id')}'): "
                        "'InitEffect' is not supported on CBehaviorBuff."
                    )

        for attr_val in elem.attrib.values():
            if any(ord(char) > 127 for char in attr_val):
                issues.append(f"Non-ASCII attribute in {file_name}: {attr_val}")
    return issues


def validate_xml_catalogs(mod_dir: Path) -> tuple[list[str], str]:
    issues: list[str] = []
    gamedata_dir = mod_dir / "Base.SC2Data" / "GameData"
    if not gamedata_dir.is_dir():
        return issues, "not applicable (GameData directory absent)"

    xml_files = sorted(gamedata_dir.glob("*.xml"))
    for xml_file in xml_files:
        try:
            parser = ET.XMLParser(target=ET.TreeBuilder(insert_comments=True))
            tree = ET.parse(xml_file, parser=parser)
            root = tree.getroot()
        except ET.ParseError as e:
            issues.append(f"XML parse error in {xml_file.name}: {e}")
            continue
        issues.extend(validate_catalog_root(root, xml_file.name))

    xsd_issues, xsd_status = validate_xml_schemas(gamedata_dir)
    issues.extend(xsd_issues)

    return issues, xsd_status


def validate_ui_layouts(mod_dir: Path) -> list[str]:
    issues: list[str] = []
    layout_dir = mod_dir / "Base.SC2Data" / "UI" / "Layout"
    layout_files = []
    if layout_dir.is_dir():
        layout_files.extend(sorted(layout_dir.glob("*.SC2Layout")))

    maps_dir = REPO_ROOT / "Maps"
    if maps_dir.is_dir():
        layout_files.extend(sorted(maps_dir.glob("*/**/UI/Layout/*.SC2Layout")))

    valid_desc_children = {"Include", "Constant", "Frame", "Animation", "StateGroup"}

    for layout_file in layout_files:
        try:
            tree = ET.parse(layout_file)
            root = tree.getroot()
        except ET.ParseError as e:
            issues.append(f"SC2Layout XML parse error in {layout_file.name}: {e}")
            continue

        if root.tag != "Desc":
            issues.append(
                f"SC2Layout root error in {layout_file.name}: Root element must be '<Desc>', found '<{root.tag}>'."
            )

        for child in root:
            if child.tag not in valid_desc_children:
                issues.append(
                    f"SC2Layout schema warning in {layout_file.name}: Unexpected child '<{child.tag}>' directly under '<Desc>'."
                )

        content = layout_file.read_text(encoding="utf-8", errors="replace")
        for line_no, line in enumerate(content.splitlines(), start=1):
            if any(ord(c) > 127 for c in line):
                issues.append(
                    f"SC2Layout non-ASCII in {layout_file.name}:{line_no}: {line.strip()[:60]}"
                )

    return issues


def validate_galaxy_file(file_path: Path, mod_dir: Path | None = None) -> list[str]:
    issues: list[str] = []
    if not file_path.is_file():
        issues.append(f"Galaxy file not found: {file_path}")
        return issues

    content = file_path.read_text(encoding="utf-8", errors="replace")
    lines = content.splitlines()

    func_sig_re = re.compile(r"^(?:static\s+)?(\w+)\s+(\w+)\s*\([^)]*\)\s*\{?")
    var_decl_re = re.compile(r"^([a-zA-Z_]\w*(?:\[[^\]]*\])?)\s+([a-zA-Z_]\w*(?:\s*,\s*[a-zA-Z_]\w*)*)(?:\s*=\s*[^;]+)?\s*;")

    in_func = False
    func_name = ""
    seen_statement = False
    brace_depth = 0

    for line_no, line in enumerate(lines, start=1):
        stripped = line.strip()
        if stripped.startswith("//"):
            # Galaxy supports UTF-8 comments; non-ASCII in comments is allowed.
            # However '--' inside a comment can be mis-tokenized as decrement.
            if "--" in line and not line.strip().startswith("//-"):
                issues.append(
                    f"Galaxy ({file_path.name}:{line_no}): '--' sequence in comment may trigger decrement tokenization: {stripped[:60]}"
                )
            continue

        clean = line.split("//")[0].strip()
        if not clean:
            continue

        # Check for include with file extension
        inc_m = re.match(r'^include\s+"([^"]+)"', clean)
        if inc_m:
            inc_path = inc_m.group(1)
            if inc_path.endswith(".galaxy") or inc_path.endswith(".h"):
                issues.append(
                    f"Galaxy ({file_path.name}:{line_no}): include path '{inc_path}' must not have a file extension."
                )
            if mod_dir is not None:
                target_galaxy = mod_dir / "Base.SC2Data" / f"{inc_path}.galaxy"
                if not target_galaxy.is_file():
                    issues.append(
                        f"Galaxy ({file_path.name}:{line_no}): included file not found: {target_galaxy}"
                    )

        for pattern, desc in DISALLOWED_GALAXY_PATTERNS:
            if pattern.search(clean):
                issues.append(f"Galaxy ({file_path.name}:{line_no}): {desc}\n  Code: {clean}")

        # Function & Variable Hoisting Tracker
        if not in_func:
            m = func_sig_re.match(clean)
            if m and not clean.endswith(";") and m.group(1) in GALAXY_PRIMITIVE_TYPES | {"void"}:
                in_func = True
                func_name = m.group(2)
                seen_statement = False
                brace_depth = clean.count("{") - clean.count("}")
                continue

        if in_func:
            brace_depth += clean.count("{") - clean.count("}")
            if brace_depth <= 0:
                in_func = False
                func_name = ""
                continue

            var_m = var_decl_re.match(clean)
            is_var_decl = False
            if var_m:
                type_candidate = var_m.group(1).split("[")[0]
                if type_candidate in GALAXY_PRIMITIVE_TYPES:
                    is_var_decl = True

            if is_var_decl:
                if seen_statement:
                    issues.append(
                        f"Galaxy ({file_path.name}:{line_no}) in '{func_name}': Variable declaration '{clean}' occurs after executable statements (violates Galaxy hoisting)."
                    )
                elif brace_depth > 1:
                    issues.append(
                        f"Galaxy ({file_path.name}:{line_no}) in '{func_name}': Variable declaration '{clean}' in nested block scope (Galaxy requires function-level hoisting)."
                    )
            else:
                if clean not in ("{", "}"):
                    seen_statement = True

    return issues


def validate_galaxy_scripts(mod_dir: Path | None) -> list[str]:
    issues: list[str] = []
    script_blocks = find_script_blocks([mod_dir] if mod_dir is not None else [])
    for block in script_blocks:
        issues.extend(validate_galaxy_file(block, mod_dir))

    if mod_dir is not None:
        scripts_dir = mod_dir / "Base.SC2Data" / "Scripts"
        func_locations: dict[str, list[str]] = {}
        func_sig_re = re.compile(r"^(?:static\s+)?([a-zA-Z_]\w*)\s+([a-zA-Z_]\w*)\s*\([^)]*\)\s*\{?")

        if scripts_dir.is_dir():
            for script_file in sorted(scripts_dir.glob("*.galaxy")):
                for line_no, line in enumerate(script_file.read_text(encoding="utf-8").splitlines(), start=1):
                    clean = line.split("//")[0].strip()
                    m = func_sig_re.match(clean)
                    if m and not clean.endswith(";"):
                        ret_type, func_name = m.group(1), m.group(2)
                        if ret_type in GALAXY_PRIMITIVE_TYPES | {"void"}:
                            func_locations.setdefault(func_name, []).append(f"{script_file.name}:{line_no}")

            for func_name, locs in func_locations.items():
                if len(locs) > 1:
                    issues.append(
                        f"Galaxy: Duplicate function definition '{func_name}' found at: {', '.join(locs)}"
                    )

    return issues


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run static validation checks on SC2 XML catalogs, UI layouts, and Galaxy scripts."
    )
    parser.add_argument("--mod-dir", help="Explicit path to .SC2Mod component directory")
    args = parser.parse_args()

    mods = find_local_mods(args.mod_dir)
    if not mods:
        print("ERROR: No .SC2Mod directory found to validate.")
        print("Pass --mod-dir or correct agent-config.json (SC2_MODS_PATH is a fallback).")
        return 2
    primary_mod = mods[0] if mods else None

    print("Running static validation checks...")
    catalog_file_count = sum(
        len(list((mod / "Base.SC2Data" / "GameData").glob("*.xml")))
        for mod in mods
        if (mod / "Base.SC2Data" / "GameData").is_dir()
    )
    layout_file_count = sum(
        len(list((mod / "Base.SC2Data" / "UI" / "Layout").glob("*.SC2Layout")))
        for mod in mods
        if (mod / "Base.SC2Data" / "UI" / "Layout").is_dir()
    )
    galaxy_file_count = len(find_script_blocks([primary_mod])) if primary_mod else 0
    print(f"Target: {primary_mod}")
    print(
        "Scanned inputs: "
        f"{catalog_file_count} catalog XML, "
        f"{layout_file_count} layout, "
        f"{galaxy_file_count} hand-authored Galaxy file(s)"
    )
    xml_issues: list[str] = []
    xsd_statuses: list[str] = []
    layout_issues: list[str] = []
    for mod in mods:
        mod_xml_issues, xsd_status = validate_xml_catalogs(mod)
        xml_issues.extend(mod_xml_issues)
        xsd_statuses.append(f"{mod.name}: {xsd_status}")
        layout_issues.extend(validate_ui_layouts(mod))

    galaxy_issues = validate_galaxy_scripts(primary_mod)

    total_issues = len(xml_issues) + len(layout_issues) + len(galaxy_issues)

    print("\n" + "=" * 60)
    print("STATIC VALIDATION RESULTS")
    print("=" * 60)
    print(f"XML Catalogs:   {len(xml_issues)} issue(s)")
    for status in xsd_statuses:
        print(f"  [XSD] {status}")
    for issue in xml_issues:
        print(f"  [XML ERROR] {issue}")

    print(f"UI Layouts:     {len(layout_issues)} issue(s)")
    for issue in layout_issues:
        print(f"  [LAYOUT ERROR] {issue}")

    print(f"Galaxy Script:  {len(galaxy_issues)} issue(s)")
    for issue in galaxy_issues:
        print(f"  [GALAXY ERROR] {issue}")

    print("=" * 60)
    if total_issues == 0:
        print("Pre-flight check PASSED cleanly.")
        return 0
    else:
        print(f"Pre-flight check FAILED with {total_issues} issue(s).")
        return 1


if __name__ == "__main__":
    sys.exit(main())
